# Generated by Django 4.2.3 on 2023-07-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="memo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
