# Generated by Django 4.2.1 on 2023-08-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0003_subtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="parent_subtask",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_subtasks",
                to="todoapp.subtask",
            ),
        ),
    ]
