# Generated by Django 4.2.1 on 2023-08-02 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0004_subtask_parent_subtask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="parent_task",
        ),
        migrations.DeleteModel(
            name="SubTask",
        ),
    ]
